# Generated by Django 4.0 on 2023-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
