# Generated by Django 4.0 on 2023-03-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0002_alter_content_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='c_type',
            field=models.CharField(choices=[('MOV', 'movie'), ('TVS', 'tv show'), ('DOC', 'documentary')], default='MOV', max_length=25),
        ),
        migrations.AddField(
            model_name='content',
            name='lang',
            field=models.CharField(default='ENG', max_length=15),
        ),
    ]
