# Generated by Django 4.0 on 2023-03-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0004_streamplatform_content_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_list', to='core_watch_it.streamplatform'),
        ),
    ]
