# Generated by Django 4.0 on 2023-03-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0005_content_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_list', to='core_watch_it.streamplatform'),
        ),
    ]
