# Generated by Django 4.0 on 2023-03-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_is_staff'),
        ('core_watch_it', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='core_user.user'),
            preserve_default=False,
        ),
    ]
