# Generated by Django 4.0 on 2023-03-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_is_staff'),
        ('core_watch_it', '0008_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='count_raing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core_user.user'),
        ),
    ]
