# Generated by Django 4.0 on 2023-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0009_review_count_raing_review_total_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='count_raing',
        ),
        migrations.RemoveField(
            model_name='review',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='content',
            name='count_raing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
