# Generated by Django 4.0 on 2023-03-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0010_remove_review_count_raing_remove_review_total_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='count_raing',
            new_name='count_rating',
        ),
    ]
