# Generated by Django 4.0 on 2023-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0012_content_certificate_content_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='trailer_link',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
