# Generated by Django 4.0 on 2023-03-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0013_content_trailer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core_watch_it.content')),
            ],
        ),
    ]
