# Generated by Django 4.0 on 2023-03-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_watch_it', '0015_contentpicture_delete_contentpictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpicture',
            old_name='pictures',
            new_name='picture',
        ),
    ]
